spring.application.name=api

# Mybatis
mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.sele906.chaekeodi
mybatis.configuration.map-underscore-to-camel-case=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Library Data
library.api.base-url=https://data4library.kr
library.api.auth-key=${LIB_API_KEY}